name: C++ Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Install GoogleTest
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Compile main program
      run: g++ -o student_database main.cpp -std=c++11

    - name: Compile tests
      run: g++ -o run_tests test_main.cpp -lgtest -lgtest_main -lpthread -std=c++11

    - name: Run tests
      run: ./run_tests
