name: C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake

    - name: Compile main program
      run: |
        echo "Compiling main program..."
        cd StudentDatabase
        g++ -o student_database src/main.cpp -std=c++11

    - name: Setup GoogleTest
      run: |
        git clone https://github.com/google/googletest.git -b release-1.12.1
        cd googletest
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr
        make -j4
        sudo make install

    - name: Compile and run tests
      run: |
        cd StudentDatabase
        g++ -o run_tests test/test.cpp -I../googletest/googletest/include -lgtest -lgtest_main -lpthread -std=c++11
        ./run_tests
